max-string-length: 24 #максимальная длина голограммы
max-lines: 6 #максимальное количество линий у голограммы
using-worldguard: true #проверка на регион
price-per-symbol: 10 #цена за символ
auto-save-timings: 300 #Раз в сколько секунд выполнять авто сохранение. Если Ваш сервер никогда не крашится то вы можете поставить значение -1
groups: #Сколько голограм может создать игрок, игроку необходимо дать следующие право pholo.groups.default чтобы он смог создавать 5. Если игроку не выдать право то он не сможет создавать голограммы
  default: 5
  vip: 10
  admin: 20
msg:
  unknown-command: '&cИспользуйте&f -> /pholo <create/del/move/addLine/removeLine>'
  create-warning: '&cПравильное написание -> /pholo create <имя> <текст>'
  delete-warning: '&cПравильное написание -> /pholo del <имя>'
  move-warning: '&cПравильное написание -> /pholo move <имя>'
  addline-warning: '&cПравильное написание -> /pholo addLine <имя> <текст>'
  removeLine-warning: '&cПравильное написание -> /pholo removeLine <имя> <номер строки>'
  only-player: 'PX Доступно только для игроков!'
  no-prem: '&cУ Вас нет разрешения!'
  max-string-length-error: '&cСтрочка слишком длинная!'
  bad-word: '&cЗапрещено использование таких слов!'
  pholo-paid: '&aУспешно! &fC Вашего баланса было списано &a{paid}$'
  pholo-paid-error: '&cВам необходимо иметь минимум &a{price}$!'
  pholo-name-error: '&cГолограмма с таким именем уже существует!'
  pholo-remove: '&aГолограмма удаленна!'
  pholo-not-found: '&cГолограммы не существует!'
  pholo-player-not-owner: '&cВы не владеете голограммой с таким именем!'
  pholo-move: '&aГолограмма передвинута!'
  pholo-addline-error: '&cНельзя добавить больше строк!'
  pholo-addline: '&aЛиния добавлена!'
  pholo-line-not-found: '&cЛинии с таким номером нет!'
  pholo-line-remove: '&aЛиния удалена!'
  pholo-worldguard: '&cВы не можете создать голограмму в чужом регионе!'
  pholo-max-holo: "&cВы не можете создать больше голограмм"

#Добавлять слова в нижнем регистре! Не нужно дублировать слова с заменой букв на английские плагин сам определит что chmoshnik это запрещённое слово хоть его и нет в словаре. Словарь нашёл в инете так-что там есть транслит
#Естественно плагин обходит изменение регистра: ПлОхОе СлОвО. Также плагин обходит чёрточки между словами: т-о-ж-е п_л_о_х-о-е с-л-о-в-о
#Цветовые коды тоже обходятся, кроме hex цветов, можно добавить "#" в black-list, чтобы запретить hex цвета.
#Плагин может ругаться на безобидные слова содержащие мат поэтому есть white-list
#Словари можно искать по такому или похожему запросу: Список плохих слов для Дискорда
#Если в словаре есть часть мата "чмо" то плагин будет ругаться и на "чмошник", в обратную сторону не работает
white-list:
  - 'сабля'
black-list:
  - 'http'
  - '.org'
  - '.ru'
  - '.com'
  - 'сайт'
  - 'донат'
  - '@'
  - 't.me'
  - '/'
  - 'telegram'
  - 'tele'
  - 'сервер'
  - 'ip'
  - 'vk'
  - 'айпи'
  - 'гей'
  - 'гомо'
  - '6ля'
  - '6лядь'
  - '6лять'
  - 'b3ъeб'
  - 'cock'
  - 'cunt'
  - 'e6aль'
  - 'ebal'
  - 'eblan'
  - 'eбaл'
  - 'eбaть'
  - 'eбyч'
  - 'eбать'
  - 'eбет'
  - 'eблантий'
  - 'fuck'
  - 'fucker'
  - 'fucking'
  - 'xyев'
  - 'xyй'
  - 'xyя'
  - 'xуе,xуй'
  - 'xую'
  - 'zaeb'
  - 'zaebal'
  - 'zaebali'
  - 'zaebat'
  - 'архипиздрит'
  - 'ахуел'
  - 'ахуеть'
  - 'бздение'
  - 'бздеть'
  - 'бздех'
  - 'бздецы'
  - 'бздит'
  - 'бздицы'
  - 'бздло'
  - 'бзднуть'
  - 'бздун'
  - 'бздунья'
  - 'бздюха'
  - 'бздюшка'
  - 'бздюшко'
  - 'бля'
  - 'блябу'
  - 'блябуду'
  - 'бляд'
  - 'бляди'
  - 'блядина'
  - 'блядище'
  - 'блядки'
  - 'блядовать'
  - 'блядство'
  - 'блядун'
  - 'блядуны'
  - 'блядунья'
  - 'блядь'
  - 'блядюга'
  - 'блять'
  - 'вафел'
  - 'вафлер'
  - 'взъебка'
  - 'взьебка'
  - 'взьебывать'
  - 'въеб'
  - 'въебался'
  - 'въебенн'
  - 'въебусь'
  - 'въебывать'
  - 'выблядок'
  - 'выблядыш'
  - 'выеб'
  - 'выебать'
  - 'выебен'
  - 'выебнулся'
  - 'выебон'
  - 'выебываться'
  - 'выпердеть'
  - 'высраться'
  - 'выссаться'
  - 'вьебен'
  - 'гавно'
  - 'гавнюк'
  - 'гавнючка'
  - 'гамно'
  - 'гандон'
  - 'гнид'
  - 'гнида'
  - 'гниды'
  - 'говенка'
  - 'говенный'
  - 'говешка'
  - 'говназия'
  - 'говнецо'
  - 'говнище'
  - 'говно'
  - 'говноед'
  - 'говнолинк'
  - 'говночист'
  - 'говнюк'
  - 'говнюха'
  - 'говнядина'
  - 'говняк'
  - 'говняный'
  - 'говнять'
  - 'гондон'
  - 'доебываться'
  - 'долбоеб'
  - 'долбоящер'
  - 'дрисня'
  - 'дрист'
  - 'дристануть'
  - 'дристать'
  - 'дристун'
  - 'дристуха'
  - 'дрочелло'
  - 'дрочена'
  - 'дрочила'
  - 'дрочилка'
  - 'дрочистый'
  - 'дрочить'
  - 'дрочка'
  - 'дрочун'
  - 'е6ал'
  - 'е6ут'
  - 'ебтвоюмать'
  - 'ебaн'
  - 'ебaть'
  - 'ебyч'
  - 'ебал'
  - 'ебало'
  - 'ебальник'
  - 'ебан'
  - 'ебанамать'
  - 'ебанат'
  - 'ебаная'
  - 'ебанический'
  - 'ебанный'
  - 'ебанныйврот'
  - 'ебаное'
  - 'ебануть'
  - 'ебануться'
  - 'ебаную'
  - 'ебаный'
  - 'ебанько'
  - 'ебарь'
  - 'ебат'
  - 'ебатория'
  - 'ебать'
  - 'ебатькопать'
  - 'ебаться'
  - 'ебашить'
  - 'ебена'
  - 'ебет'
  - 'ебец'
  - 'ебик'
  - 'ебин'
  - 'ебись'
  - 'ебическая'
  - 'ебки'
  - 'ебла'
  - 'еблан'
  - 'ебливый'
  - 'еблище'
  - 'ебло'
  - 'еблыст'
  - 'ебля'
  - 'ебн'
  - 'ебнуть'
  - 'ебнуться'
  - 'ебня'
  - 'ебошить'
  - 'ебская'
  - 'ебский'
  - 'ебун'
  - 'ебут'
  - 'ебуч'
  - 'ебуче'
  - 'ебучее'
  - 'ебучий'
  - 'ебучим'
  - 'ебущ'
  - 'ебырь'
  - 'елда'
  - 'елдак'
  - 'елдачить'
  - 'жопа'
  - 'жопу'
  - 'заговнять'
  - 'задрачивать'
  - 'задристать'
  - 'задрота'
  - 'зае6'
  - 'заеб'
  - 'заеба'
  - 'заебал'
  - 'заебанец'
  - 'заебастая'
  - 'заебастый'
  - 'заебать'
  - 'заебаться'
  - 'заебашить'
  - 'заебистое'
  - 'заебистые'
  - 'заебистый'
  - 'заебись'
  - 'заебошить'
  - 'заебываться'
  - 'залуп'
  - 'залупа'
  - 'залупаться'
  - 'залупить'
  - 'залупиться'
  - 'замудохаться'
  - 'запиздячить'
  - 'засерать'
  - 'засерун'
  - 'засеря'
  - 'засирать'
  - 'засрун'
  - 'захуячить'
  - 'заябестая'
  - 'злоеб'
  - 'злоебучая'
  - 'злоебучее'
  - 'злоебучий'
  - 'ибанамат'
  - 'ибонех'
  - 'изговнять'
  - 'изговняться'
  - 'изъебнуться'
  - 'ипать'
  - 'ипаться'
  - 'ипаццо'
  - 'Какдвапальцаобоссать'
  - 'конча'
  - 'курва'
  - 'курвятник'
  - 'лох'
  - 'лошарa'
  - 'лошара'
  - 'лошары'
  - 'лошок'
  - 'лярва'
  - 'малафья'
  - 'манда'
  - 'мандавошек'
  - 'мандавошка'
  - 'мандавошки'
  - 'мандей'
  - 'мандень'
  - 'мандеть'
  - 'мандища'
  - 'мандой'
  - 'манду'
  - 'мандюк'
  - 'минет'
  - 'минетчик'
  - 'минетчица'
  - 'млять'
  - 'мокрощелка'
  - 'мразь'
  - 'мудak'
  - 'мудaк'
  - 'мудаг'
  - 'мудак'
  - 'муде'
  - 'мудель'
  - 'мудеть'
  - 'муди'
  - 'мудил'
  - 'мудила'
  - 'мудистый'
  - 'мудня'
  - 'мудоеб'
  - 'мудозвон'
  - 'мудоклюй'
  - 'нахер'
  - 'нахуй'
  - 'набздел'
  - 'набздеть'
  - 'наговнять'
  - 'надристать'
  - 'надрочить'
  - 'наебать'
  - 'наебет'
  - 'наебнуть'
  - 'наебнуться'
  - 'наебывать'
  - 'напиздел'
  - 'напиздели'
  - 'напиздело'
  - 'напиздили'
  - 'насрать'
  - 'настопиздить'
  - 'нахрен'
  - 'нахуйник'
  - 'неебет'
  - 'невротебучий'
  - 'невъебенно'
  - 'нехира'
  - 'нехрен'
  - 'Нехуй'
  - 'нехуйственно'
  - 'ниибацо'
  - 'ниипацца'
  - 'ниипаццо'
  - 'ниипет'
  - 'никуя'
  - 'нихера'
  - 'нихуя'
  - 'обдристаться'
  - 'обосранец'
  - 'обосрать'
  - 'обосцать'
  - 'обосцаться'
  - 'обсирать'
  - 'объебос'
  - 'обьебатьобьебос'
  - 'однохуйственно'
  - 'опездал'
  - 'опизде'
  - 'опизденивающе'
  - 'остоебенить'
  - 'остопиздеть'
  - 'отмудохать'
  - 'отпиздить'
  - 'отпиздячить'
  - 'отпороть'
  - 'отъебись'
  - 'охуевательский'
  - 'охуевать'
  - 'охуевающий'
  - 'охуел'
  - 'охуенно'
  - 'охуеньчик'
  - 'охуеть'
  - 'охуительно'
  - 'охуительный'
  - 'охуяньчик'
  - 'охуячивать'
  - 'охуячить'
  - 'очкун'
  - 'падла'
  - 'падонки'
  - 'падонок'
  - 'паскуда'
  - 'педерас'
  - 'педик'
  - 'педрик'
  - 'педрила'
  - 'педрилло'
  - 'педрило'
  - 'педрилы'
  - 'пездень'
  - 'пездит'
  - 'пездишь'
  - 'пездо'
  - 'пездят'
  - 'пердануть'
  - 'пердеж'
  - 'пердение'
  - 'пердеть'
  - 'пердильник'
  - 'перднуть'
  - 'пердун'
  - 'пердунец'
  - 'пердунина'
  - 'пердунья'
  - 'пердуха'
  - 'пердь'
  - 'переебок'
  - 'пернуть'
  - 'пи3д'
  - 'пи3де'
  - 'пи3ду'
  - 'пиzдец'
  - 'пидар'
  - 'пидарaс'
  - 'пидарас'
  - 'пидарасы'
  - 'пидары'
  - 'пидор'
  - 'пидорасы'
  - 'пидорка'
  - 'пидорок'
  - 'пидоры'
  - 'пидрас'
  - 'пизда'
  - 'пиздануть'
  - 'пиздануться'
  - 'пиздарваньчик'
  - 'пиздато'
  - 'пиздатое'
  - 'пиздатый'
  - 'пизденка'
  - 'пизденыш'
  - 'пиздеть'
  - 'пиздец'
  - 'пиздит'
  - 'пиздить'
  - 'пиздиться'
  - 'пиздишь'
  - 'пиздища'
  - 'пиздище'
  - 'пиздобол'
  - 'пиздоболы'
  - 'пиздобратия'
  - 'пиздоватая'
  - 'пиздоватый'
  - 'пиздолиз'
  - 'пиздонутые'
  - 'пиздорванец'
  - 'пиздорванка'
  - 'пиздострадатель'
  - 'пизду'
  - 'пиздуй'
  - 'пиздун'
  - 'пиздунья'
  - 'пизды'
  - 'пиздюга'
  - 'пиздюк'
  - 'пиздюлина'
  - 'пиздюля'
  - 'пиздят'
  - 'пиздячить'
  - 'писбшки'
  - 'писька'
  - 'писькострадатель'
  - 'писюн'
  - 'писюшка'
  - 'похуй'
  - 'похую'
  - 'подговнять'
  - 'подонки'
  - 'подонок'
  - 'подъебнуть'
  - 'подъебнуться'
  - 'поебать'
  - 'поебень'
  - 'поебываает'
  - 'поскуда'
  - 'посрать'
  - 'потаскуха'
  - 'потаскушка'
  - 'похер'
  - 'похерил'
  - 'похерила'
  - 'похерили'
  - 'похеру'
  - 'похрен'
  - 'похрену'
  - 'похуист'
  - 'похуистка'
  - 'придурок'
  - 'приебаться'
  - 'припиздень'
  - 'припизднутый'
  - 'припиздюлина'
  - 'пробзделся'
  - 'проблядь'
  - 'проеб'
  - 'проебанка'
  - 'проебать'
  - 'промандеть'
  - 'промудеть'
  - 'пропизделся'
  - 'пропиздеть'
  - 'пропиздячить'
  - 'раздолбай'
  - 'разхуячить'
  - 'разъеб'
  - 'разъеба'
  - 'разъебай'
  - 'разъебать'
  - 'распиздай'
  - 'распиздеться'
  - 'распиздяй'
  - 'распиздяйство'
  - 'распроеть'
  - 'сволота'
  - 'сволочь'
  - 'сговнять'
  - 'секель'
  - 'серун'
  - 'серька'
  - 'сестроеб'
  - 'сикель'
  - 'сила'
  - 'сирать'
  - 'сирывать'
  - 'соси'
  - 'спиздел'
  - 'спиздеть'
  - 'спиздил'
  - 'спиздила'
  - 'спиздили'
  - 'спиздит'
  - 'спиздить'
  - 'срака'
  - 'сраку'
  - 'сраный'
  - 'сранье'
  - 'срать'
  - 'срун'
  - 'ссака'
  - 'ссышь'
  - 'стерва'
  - 'страхопиздище'
  - 'сука'
  - 'суки'
  - 'суходрочка'
  - 'сучара'
  - 'сучий'
  - 'сучка'
  - 'сучко'
  - 'сучонок'
  - 'сучье'
  - 'сцание'
  - 'сцать'
  - 'сцука'
  - 'сцуки'
  - 'сцуконах'
  - 'сцуль'
  - 'сцыха'
  - 'сцышь'
  - 'съебаться'
  - 'сыкун'
  - 'трахае6'
  - 'трахаеб'
  - 'трахатель'
  - 'ублюдок'
  - 'уебать'
  - 'уебища'
  - 'уебище'
  - 'уебищное'
  - 'уебк'
  - 'уебки'
  - 'уебок'
  - 'урюк'
  - 'усраться'
  - 'ушлепок'
  - 'хуяра'
  - 'хyе'
  - 'хyй'
  - 'хyйня'
  - 'хамло'
  - 'хер'
  - 'херня'
  - 'херовато'
  - 'херовина'
  - 'херовый'
  - 'хитровыебанный'
  - 'хитрожопый'
  - 'хуeм'
  - 'хуе'
  - 'хуевато'
  - 'хуевенький'
  - 'хуевина'
  - 'хуево'
  - 'хуевый'
  - 'хуек'
  - 'хуел'
  - 'хуем'
  - 'хуенч'
  - 'хуеныш'
  - 'хуенький'
  - 'хуеплет'
  - 'хуепромышленник'
  - 'хуерик'
  - 'хуерыло'
  - 'хуесос'
  - 'хуесоска'
  - 'хуета'
  - 'хуетень'
  - 'хуею'
  - 'хуи'
  - 'хуй'
  - 'хуйком'
  - 'хуйло'
  - 'хуйня'
  - 'хуйрик'
  - 'хуище'
  - 'хуля'
  - 'хую'
  - 'хуюл'
  - 'хуя'
  - 'хуяк'
  - 'хуякать'
  - 'хуякнуть'
  - 'хуясе'
  - 'хуячить'
  - 'целка'
  - 'чмо'
  - 'чмошник'
  - 'чмырь'
  - 'шалава'
  - 'шалавой'
  - 'шараебиться'
  - 'шлюха'
  - 'шлюхой'
  - 'шлюшка'
  - 'ябывает'
data:
  player:
    - http